/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2018-04-13 02:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("Design by TEMPLATED\r\n");
      out.write("http://templated.co\r\n");
      out.write("Released for free under the Creative Commons Attribution License\r\n");
      out.write("\r\n");
      out.write("Name       : GreenOrange  \r\n");
      out.write("Description: A two-column, fixed-width design with dark color scheme.\r\n");
      out.write("Version    : 1.0\r\n");
      out.write("Released   : 20110411\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Greenorange by TEMPLATED</title>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("    <div id=\"search\" >\r\n");
      out.write("\t\t\t\t\t<form method=\"get\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"s\" id=\"search-text\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" id=\"search-submit\" value=\"GO\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t  </div>\r\n");
      out.write("    \r\n");
      out.write("\t  <ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \t<li><a href=\"#\">é¦é </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">è¨»å</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">ç»å¥</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("    <img src=\"images/icon2.png\" alt=\"\" width=\"235\" height=\"84\" /></div>\r\n");
      out.write("\t<!-- end #menu -->\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("\t<!-- end #header -->\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("    <div id=\"sidebar2\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<div id=\"whattoeat\" style=\"font-size:xx-large\" align=\"center\" >åä»éº¼å¢?</div>\r\n");
      out.write("                <br />\r\n");
      out.write("                <div style=\"height:180px\"><img src=\"images/circle.png\" alt=\"\" width=\"178\" height=\"181\" /></div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"lightfood\">\r\n");
      out.write("                \r\n");
      out.write("                <div style=\"font-size:xx-large\" align=\"center\">è¼é£å</div>\r\n");
      out.write("                <br />\r\n");
      out.write("                <table>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"172\">\r\n");
      out.write("               <div style=\"height:180px\">è¼é£å</div>\r\n");
      out.write("               </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <td height=\"86\">\r\n");
      out.write("               <div>æå­</div>\r\n");
      out.write("               <br />\r\n");
      out.write("               <div>æå­</div>\r\n");
      out.write("               </td>\r\n");
      out.write("               </table>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               </div>\r\n");
      out.write("              \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- end #sidebar2 -->\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"sidebar\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"clear: both;\" align=\"center\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<div id=\"category\" style=\"font-size:xx-large\" align=\"center\" ba><b>åé¡</b></div>\r\n");
      out.write("                <br />\r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>å°å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>è¥¿å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>æ¥å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>éå¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>ç¾å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>ç¾©å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>æ¸¯å¼æç</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>æ©åé¤</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>ç«éé¡</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>é¤çè¨è³¼</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>é£²æ</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<h2>å¶ä»</h2>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end #sidebar -->\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\"><a href=\"#\"><img src=\"images/1.png\" alt=\"\" width=\"36\" height=\"30\" />å°åç±éç¾é£é¤å»³</a></h2>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t  <div class=\"entry\">\r\n");
      out.write("               <table width=\"431\" height=\"256\">\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div>åç</div></td>\r\n");
      out.write("               <td width=\"113\"> <div>åç</div></td>\r\n");
      out.write("               <td width=\"111\"><div>åç</div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div>æå­</div></td>\r\n");
      out.write("               <td width=\"113\"> <div>æå­</div></td>\r\n");
      out.write("               <td width=\"111\"><div>æå­</div></td>\r\n");
      out.write("               \r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("             <td height=\"114\"><div>åç</div></td>\r\n");
      out.write("             <td><div>åç</div></td>\r\n");
      out.write("             <td><div>åç</div></td>                \r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div>æå­</div></td>\r\n");
      out.write("               <td width=\"113\"> <div>æå­</div></td>\r\n");
      out.write("               <td width=\"111\"><div>æå­</div></td>\r\n");
      out.write("                <td width=\"73\"><div>æ´å¤</div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </table> \r\n");
      out.write("                  \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"post\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\"><a href=\"#\"><img src=\"images/1.png\" alt=\"\" width=\"36\" height=\"30\" />æ°åç±éç¾é£é¤å»³</a></h2>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <div class=\"entry\">\r\n");
      out.write("               <table width=\"431\" height=\"256\">\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div align=\"center\">åç</div></td>\r\n");
      out.write("               <td width=\"113\"> <div align=\"center\">åç</div></td>\r\n");
      out.write("               <td width=\"111\"><div align=\"center\">åç</div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div align=\"center\">æå­</div></td>\r\n");
      out.write("               <td width=\"113\"> <div align=\"center\">æå­</div></td>\r\n");
      out.write("               <td width=\"111\"><div align=\"center\">æå­</div></td>\r\n");
      out.write("               \r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("             <td height=\"114\"><div align=\"center\">åç</div></td>\r\n");
      out.write("             <td><div align=\"center\">åç</div></td>\r\n");
      out.write("             <td><div align=\"center\">åç</div></td>                \r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t   <td width=\"114\"> <div align=\"center\">æå­</div></td>\r\n");
      out.write("               <td width=\"113\"> <div align=\"center\">æå­</div></td>\r\n");
      out.write("               <td width=\"111\"><div align=\"center\">æå­</div></td>\r\n");
      out.write("                <td width=\"73\"><div align=\"center\">æ´å¤...</div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                   </table> \r\n");
      out.write("                  \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t\t<!-- end #content -->\r\n");
      out.write("        \r\n");
      out.write("\t<div id=\"page-bgtop\">\r\n");
      out.write("\t<div id=\"page-bgbtm\">\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t\t\r\n");
      out.write("      \r\n");
      out.write("\t\t<div style=\"clear: both;\" align=\"right\">åé¡åå ±</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #page -->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t  <p>&copy; Untitled. All rights reserved. Design by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>.\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
